import = ["/home/elliot/.config/alacritty/colors.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 9.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "mnonospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "full"
opacity = 0.9
title = "fsociety"

[window.padding]
x = 10
y = 10
