- name: Copy custom podman configuration
  ansible.builtin.copy:
    src: misc/podman-config.conf
    dest: "/etc/containers/registries.conf.d/podman-config.conf"
    remote_src: false
  tags:
   - configurations
   - podman

- name: Enable podman service for container runtime
  ansible.builtin.systemd_service:
   state: restarted
   daemon_reload: true
   name: podman
   enabled: true
  tags:
    - configurations
    - podman
