# Change default shell
- name: Change user shell
  user:
    name: "{{ user_name }}"
    shell: /usr/bin/fish
  tags:
    - configurations
    - shell

- name: Copy fish functions
  ansible.builtin.copy:
    src: config/fish/functions
    dest: "{{ user_home_dir }}/.config/fish/functions"
    remote_src: false
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0755'
  tags:
   - configurations
   - shell

- name: Check if oh-my-fish is installed
  stat:
    path: '/etc/omf.installed'
  register: omf
  tags:
   - configurations
   - shell

- name: Clone oh-my-fish repo
  git:
    repo: 'https://github.com/oh-my-fish/oh-my-fish'
    dest: '/tmp/omf'
    clone: yes
  when: not omf.stat.exists
  tags:
   - configurations
   - shell

- name: Install oh-my-fish
  become: true
  become_user: '{{ user_name }}'
  command: /tmp/omf/bin/install -y --offline --noninteractive
  when: not omf.stat.exists
  tags:
   - configurations
   - shell

- name: Mark oh-my-fish installed with /etc/omf.installed
  file:
    path: /etc/omf.installed
    state: touch
  tags:
   - configurations
   - shell

- name: Install oh-my-fish
  become: true
  become_user: '{{ user_name }}'
  shell:
    cmd: "omf install {{ item }}"
    executable: /usr/bin/fish
  when: omf.stat.exists
  with_items:
    - https://github.com/jhillyerd/plugin-git
    - https://github.com/blackjid/plugin-kubectl
  tags:
   - configurations
   - shell

- name: Download fisher
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish
    dest: /tmp/fisher.fish
  tags:
   - configurations
   - shell

- name: Install fisher
  become: true
  become_user: '{{ user_name }}'
  #command: chdir=/tmp "source fisher.fish && fisher install jorgebucaran/fisher"
  shell:
    cmd: "source fisher.fish & fisher install jorgebucaran/fisher"
    executable: /usr/bin/fish
    chdir: /tmp
  tags:
   - configurations
   - shell

- name: Install fisher plugins
  become: true
  become_user: '{{ user_name }}'
  shell:
    cmd: "fisher install {{ item }}"
    executable: /usr/bin/fish
  with_items:
    - PatrickF1/fzf.fish
  tags:
   - configurations
   - shell
