---
- name: Provision Desktop Environment
  hosts: local
  become: true
  vars_files:
    - vars.yml
  vars:
    apt_package_file: "apt_packages.txt"
    apt_package_list: "{{ lookup('file', apt_package_file) | split('\n') }}"
    user_home_dir: "{{ lookup('env', 'HOME') }}"
    user_name: "{{ lookup('env', 'USER') }}"
    wlan_interface: ""
  roles:
    - core
    - configurations
