# Install base packages and others
- name:  Install the following packages {{ pacman_package_list }} through pacman
  community.general.pacman:
    name: "{{ pacman_package_list }}"
    state: present
    update_cache: true
  become: true
  tags:
    - packages
    - pacman
