#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


for monitor in $(xrandr -q | grep -w 'connected' | cut -d' ' -f1); do
    if [ "$monitor" = "eDP-1" ] ; then
        xrandr --output eDP-1 --mode 1920x1080 --rate 60 --rotate normal
    fi
    if [ "$monitor" = "DP-1" ]; then  
        xrandr --output "$monitor" --mode 1920x1080 --rate 60 --rotate normal --left-of eDP-1 --output 
        bspc monitor "$monitor" -d '󰊠' '󰊠' '󰊠' '󰊠' '󰊠' '󰊠'
    fi
    #bspc monitor "$monitor" -d '' '' '' '' '' ''
done

bspc config window_gap					6
bspc config split_ratio					0.51
bspc config single_monocle				true
bspc config borderless_monocle			false
bspc config gapless_monocle				false

bspc config focus_follows_pointer		true
bspc config pointer_follows_focus		false
bspc config pointer_motion_interval		5
bspc config pointer_modifier			mod4
bspc config pointer_action1				move
bspc config pointer_action2				resize_side
bspc config pointer_action3				resize_corner

# Colors
# bspc config normal_border_color "#44475a"
# bspc config active_border_color "#a385dc"
# bspc config focused_border_color "#1E90FF"
# bspc config presel_feedback_color "#6272a4"

bspc config border_width 2
bspc config top_padding 48
bspc config bottom_padding 30
bspc config left_padding 2
bspc config right_padding 2
bspc config normal_border_color "#543f66"
bspc config active_border_color "#543f66"
bspc config focused_border_color "#465b80"
bspc config presel_feedback_color "#3f5273"

## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

#bspc wm --adopt-orphans
bspc rule -a scratch sticky=on state=floating focus=on

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Autostart applications
sxhkd &

picom --config $HOME/.config/picom/picom.conf &

# Wallpapers
feh -z --no-fehbg --bg-fill /usr/share/backgrounds

# Bar
# By the moment, the dock using EWW is not created
# "$HOME/.config/eww/launch.sh"

dunst &

# Launch polybar using the script
"$HOME"/.config/polybar/launch.sh

# Launch polkit
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }

# Fix cursor.
xsetroot -cursor_name left_ptr
